// frontend/src/components/HorrorScreen.vue
<template>
  <div class="horror-overlay" :class="{ 'fade-out': fadingOut }">
    <!-- Typewriter mode -->
    <div v-if="type === 'typewriter'" class="horror-text typewriter-text">
      {{ displayedText }}<span class="cursor">|</span>
    </div>

    <!-- Shatter mode -->
    <div v-if="type === 'shatter'" class="shatter-container">
      <div v-if="!shattering" class="horror-text shatter-text" :class="{ 'glitch': glitching }">
        {{ text }}
      </div>
      <div v-if="shattering" class="shatter-grid">
        <div
          v-for="i in shardCount"
          :key="i"
          class="shard"
          :style="getShardStyle(i)"
        ></div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'

const props = defineProps<{
  type: 'typewriter' | 'shatter'
  text: string
}>()

const emit = defineEmits<{
  done: []
}>()

const displayedText = ref('')
const fadingOut = ref(false)
const shattering = ref(false)
const glitching = ref(false)

const cols = 8
const rows = 6
const shardCount = cols * rows

function getShardStyle(index: number) {
  const col = (index - 1) % cols
  const row = Math.floor((index - 1) / cols)
  const angle = (Math.random() - 0.5) * 720
  const tx = (Math.random() - 0.5) * 800
  const ty = (Math.random() - 0.5) * 600 + 200
  const delay = Math.random() * 0.3

  return {
    left: `${(col / cols) * 100}%`,
    top: `${(row / rows) * 100}%`,
    width: `${100 / cols}%`,
    height: `${100 / rows}%`,
    '--angle': `${angle}deg`,
    '--tx': `${tx}px`,
    '--ty': `${ty}px`,
    '--delay': `${delay}s`,
  }
}

function typewriterEffect() {
  let i = 0
  const interval = setInterval(() => {
    if (i < props.text.length) {
      displayedText.value = props.text.slice(0, i + 1)
      i++
    } else {
      clearInterval(interval)
      setTimeout(() => {
        fadingOut.value = true
        setTimeout(() => emit('done'), 800)
      }, 1500)
    }
  }, 120)
}

function shatterEffect() {
  setTimeout(() => {
    glitching.value = true
    setTimeout(() => {
      shattering.value = true
      setTimeout(() => {
        emit('done')
      }, 1500)
    }, 1000)
  }, 2000)
}

onMounted(() => {
  if (props.type === 'typewriter') {
    setTimeout(typewriterEffect, 800)
  } else {
    shatterEffect()
  }
})
</script>

<style scoped>
.horror-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: #000;
  z-index: 99999;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: opacity 0.8s ease;
}

.horror-overlay.fade-out {
  opacity: 0;
}

.horror-text {
  color: #cc0000;
  font-size: 2rem;
  font-family: 'STKaiti', 'KaiTi', serif;
  letter-spacing: 0.15em;
  text-shadow: 0 0 10px rgba(200, 0, 0, 0.5);
  user-select: none;
}

.typewriter-text {
  min-height: 3rem;
}

.cursor {
  animation: blink 0.6s step-end infinite;
  color: #cc0000;
}

@keyframes blink {
  50% { opacity: 0; }
}

.shatter-text {
  animation: fadeInScare 0.15s ease-out;
}

@keyframes fadeInScare {
  0% {
    opacity: 0;
    transform: scale(1.5);
  }
  100% {
    opacity: 1;
    transform: scale(1);
  }
}

.shatter-text.glitch {
  animation: glitchShake 0.1s linear infinite;
}

@keyframes glitchShake {
  0% { transform: translate(0, 0); }
  25% { transform: translate(-3px, 2px); }
  50% { transform: translate(3px, -2px); }
  75% { transform: translate(-2px, -3px); }
  100% { transform: translate(2px, 3px); }
}

.shatter-container {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.shatter-grid {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
}

.shard {
  position: absolute;
  background: #000;
  border: 1px solid rgba(100, 0, 0, 0.3);
  animation: shardFly 1.2s var(--delay) ease-in forwards;
}

@keyframes shardFly {
  0% {
    transform: rotate(0deg) translate(0, 0);
    opacity: 1;
  }
  100% {
    transform: rotate(var(--angle)) translate(var(--tx), var(--ty));
    opacity: 0;
  }
}
</style>

// frontend/src/components/HorrorScreen/HorrorScreen.jsx
import { useState, useEffect, useRef, useMemo } from 'react';
import './HorrorScreen.css';

/**
 * 恐怖黑屏组件
 * type: 'typewriter' — 打字机逐字显示文本后回调 onDone
 * type: 'shatter' — 文字瞬间出现 → 屏幕破碎 → 回调 onDone
 */
export default function HorrorScreen({ type, text, onDone }) {
  const [displayedText, setDisplayedText] = useState('');
  const [fadingOut, setFadingOut] = useState(false);
  const [shattering, setShattering] = useState(false);
  const [glitching, setGlitching] = useState(false);
  const timerRef = useRef(null);

  const COLS = 8;
  const ROWS = 6;
  const shards = useMemo(() => {
    return Array.from({ length: COLS * ROWS }).map((_, i) => {
      const col = i % COLS;
      const row = Math.floor(i / COLS);
      return {
        id: i,
        left: `${(col / COLS) * 100}%`,
        top: `${(row / ROWS) * 100}%`,
        width: `${100 / COLS}%`,
        height: `${100 / ROWS}%`,
        angle: `${(Math.random() - 0.5) * 720}deg`,
        tx: `${(Math.random() - 0.5) * 800}px`,
        ty: `${(Math.random() - 0.5) * 600 + 200}px`,
        delay: `${Math.random() * 0.3}s`,
      };
    });
  }, []);

  useEffect(() => {
    const blockKeys = (e) => { e.preventDefault(); e.stopPropagation(); };
    window.addEventListener('keydown', blockKeys, true);
    window.addEventListener('keyup', blockKeys, true);
    return () => {
      window.removeEventListener('keydown', blockKeys, true);
      window.removeEventListener('keyup', blockKeys, true);
    };
  }, []);

  useEffect(() => {
    if (type === 'typewriter') {
      let i = 0;
      const timer = setTimeout(() => {
        timerRef.current = setInterval(() => {
          if (i < text.length) {
            setDisplayedText(text.slice(0, i + 1));
            i++;
          } else {
            clearInterval(timerRef.current);
            setTimeout(() => {
              setFadingOut(true);
              setTimeout(() => onDone?.(), 800);
            }, 1500);
          }
        }, 120);
      }, 800);
      return () => { clearTimeout(timer); clearInterval(timerRef.current); };
    }

    if (type === 'shatter') {
      const t1 = setTimeout(() => setGlitching(true), 2000);
      const t2 = setTimeout(() => setShattering(true), 3000);
      const t3 = setTimeout(() => onDone?.(), 4500);
      return () => { clearTimeout(t1); clearTimeout(t2); clearTimeout(t3); };
    }
  }, [type, text, onDone]);

  return (
    <div className={`horror-overlay ${fadingOut ? 'horror-overlay--fade' : ''}`}>
      {type === 'typewriter' && (
        <div className="horror-text horror-text--typewriter">
          {displayedText}<span className="horror-cursor">|</span>
        </div>
      )}

      {type === 'shatter' && !shattering && (
        <div className={`horror-text horror-text--shatter ${glitching ? 'horror-text--glitch' : ''}`}>
          {text}
        </div>
      )}

      {type === 'shatter' && shattering && (
        <div className="horror-shatter-grid">
          {shards.map((s) => (
            <div
              key={s.id}
              className="horror-shard"
              style={{
                left: s.left,
                top: s.top,
                width: s.width,
                height: s.height,
                '--angle': s.angle,
                '--tx': s.tx,
                '--ty': s.ty,
                '--delay': s.delay,
              }}
            />
          ))}
        </div>
      )}
    </div>
  );
}
